language: php

php:
  - 5.6
  - 7.0
  - 7.1
#
#before_script:
#  - composer install --prefer-source --no-interaction --dev
#  - cp .env.test .env
#  - touch database/database.sqlite
#  - php artisan migrate && php artisan passport:install
#

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source --dev

script:
  - phpunit --coverage-text --coverage-clover=coverage.clover

after_script:
  -    if [[ "$TRAVIS_PHP_VERSION" != 'hhvm' && "$TRAVIS_PHP_VERSION" != '7.0' ]]; then
         wget https://scrutinizer-ci.com/ocular.phar
         php ocular.phar code-coverage:upload --format=php-clover coverage.clover
       fi
